--- #YAML:1.0
name:                Lingua-EN-Semtags-Engine
version:             0.02
abstract:            extract semantic tags (semtags) from English text
license:             ~
author:
    - Igor Myroshnichenko <igorm@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42_01
distribution_type:   module
requires:
    Lingua::EN::Tagger:            0.11
    WordNet::QueryData:            1.46
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
